services:
  - type: web
    name: your-service-name-here
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python st.py"     # or "python3 st.py" or uvicorn...
    autoDeploy: true
